// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

//go:build no_runtime_type_checking

package datadatabricksfeatureengineeringfeature

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutApproxCountDistinctParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionApproxCountDistinct) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutApproxPercentileParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionApproxPercentile) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutAvgParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionAvg) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutCountFunctionParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionCountFunction) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutFirstParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionFirst) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutFirstDistinctParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionFirstDistinct) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutFirstNParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionFirstN) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutLastParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionLast) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutLastDistinctParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionLastDistinct) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutLastNParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionLastN) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutMaxParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionMax) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutMinParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionMin) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutStddevPopParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionStddevPop) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutStddevSampParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionStddevSamp) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutSumParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionSum) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutTimeWindowParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionTimeWindow) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutVarPopParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionVarPop) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validatePutVarSampParameters(value *DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionVarSamp) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateSetInternalValueParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewDataDatabricksFeatureEngineeringFeatureFunctionAggregationFunctionOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

