// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package permissions

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-databricks.permissions.Permissions",
		reflect.TypeOf((*Permissions)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accessControl", GoGetter: "AccessControl"},
			_jsii_.MemberProperty{JsiiProperty: "accessControlInput", GoGetter: "AccessControlInput"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "alertV2Id", GoGetter: "AlertV2Id"},
			_jsii_.MemberProperty{JsiiProperty: "alertV2IdInput", GoGetter: "AlertV2IdInput"},
			_jsii_.MemberProperty{JsiiProperty: "appName", GoGetter: "AppName"},
			_jsii_.MemberProperty{JsiiProperty: "appNameInput", GoGetter: "AppNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "authorization", GoGetter: "Authorization"},
			_jsii_.MemberProperty{JsiiProperty: "authorizationInput", GoGetter: "AuthorizationInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "clusterId", GoGetter: "ClusterId"},
			_jsii_.MemberProperty{JsiiProperty: "clusterIdInput", GoGetter: "ClusterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "clusterPolicyId", GoGetter: "ClusterPolicyId"},
			_jsii_.MemberProperty{JsiiProperty: "clusterPolicyIdInput", GoGetter: "ClusterPolicyIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dashboardId", GoGetter: "DashboardId"},
			_jsii_.MemberProperty{JsiiProperty: "dashboardIdInput", GoGetter: "DashboardIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "databaseInstanceName", GoGetter: "DatabaseInstanceName"},
			_jsii_.MemberProperty{JsiiProperty: "databaseInstanceNameInput", GoGetter: "DatabaseInstanceNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "databaseProjectName", GoGetter: "DatabaseProjectName"},
			_jsii_.MemberProperty{JsiiProperty: "databaseProjectNameInput", GoGetter: "DatabaseProjectNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "directoryId", GoGetter: "DirectoryId"},
			_jsii_.MemberProperty{JsiiProperty: "directoryIdInput", GoGetter: "DirectoryIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "directoryPath", GoGetter: "DirectoryPath"},
			_jsii_.MemberProperty{JsiiProperty: "directoryPathInput", GoGetter: "DirectoryPathInput"},
			_jsii_.MemberProperty{JsiiProperty: "experimentId", GoGetter: "ExperimentId"},
			_jsii_.MemberProperty{JsiiProperty: "experimentIdInput", GoGetter: "ExperimentIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberProperty{JsiiProperty: "instancePoolId", GoGetter: "InstancePoolId"},
			_jsii_.MemberProperty{JsiiProperty: "instancePoolIdInput", GoGetter: "InstancePoolIdInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "jobId", GoGetter: "JobId"},
			_jsii_.MemberProperty{JsiiProperty: "jobIdInput", GoGetter: "JobIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "knowledgeAssistantId", GoGetter: "KnowledgeAssistantId"},
			_jsii_.MemberProperty{JsiiProperty: "knowledgeAssistantIdInput", GoGetter: "KnowledgeAssistantIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberMethod{JsiiMethod: "markWriteOnlyAttribute", GoMethod: "MarkWriteOnlyAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "notebookId", GoGetter: "NotebookId"},
			_jsii_.MemberProperty{JsiiProperty: "notebookIdInput", GoGetter: "NotebookIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "notebookPath", GoGetter: "NotebookPath"},
			_jsii_.MemberProperty{JsiiProperty: "notebookPathInput", GoGetter: "NotebookPathInput"},
			_jsii_.MemberProperty{JsiiProperty: "objectType", GoGetter: "ObjectType"},
			_jsii_.MemberProperty{JsiiProperty: "objectTypeInput", GoGetter: "ObjectTypeInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "pipelineId", GoGetter: "PipelineId"},
			_jsii_.MemberProperty{JsiiProperty: "pipelineIdInput", GoGetter: "PipelineIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "providerConfig", GoGetter: "ProviderConfig"},
			_jsii_.MemberProperty{JsiiProperty: "providerConfigInput", GoGetter: "ProviderConfigInput"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putAccessControl", GoMethod: "PutAccessControl"},
			_jsii_.MemberMethod{JsiiMethod: "putProviderConfig", GoMethod: "PutProviderConfig"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "registeredModelId", GoGetter: "RegisteredModelId"},
			_jsii_.MemberProperty{JsiiProperty: "registeredModelIdInput", GoGetter: "RegisteredModelIdInput"},
			_jsii_.MemberMethod{JsiiMethod: "registerProviderFeatureUsage", GoMethod: "RegisterProviderFeatureUsage"},
			_jsii_.MemberProperty{JsiiProperty: "repoId", GoGetter: "RepoId"},
			_jsii_.MemberProperty{JsiiProperty: "repoIdInput", GoGetter: "RepoIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "repoPath", GoGetter: "RepoPath"},
			_jsii_.MemberProperty{JsiiProperty: "repoPathInput", GoGetter: "RepoPathInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAlertV2Id", GoMethod: "ResetAlertV2Id"},
			_jsii_.MemberMethod{JsiiMethod: "resetAppName", GoMethod: "ResetAppName"},
			_jsii_.MemberMethod{JsiiMethod: "resetAuthorization", GoMethod: "ResetAuthorization"},
			_jsii_.MemberMethod{JsiiMethod: "resetClusterId", GoMethod: "ResetClusterId"},
			_jsii_.MemberMethod{JsiiMethod: "resetClusterPolicyId", GoMethod: "ResetClusterPolicyId"},
			_jsii_.MemberMethod{JsiiMethod: "resetDashboardId", GoMethod: "ResetDashboardId"},
			_jsii_.MemberMethod{JsiiMethod: "resetDatabaseInstanceName", GoMethod: "ResetDatabaseInstanceName"},
			_jsii_.MemberMethod{JsiiMethod: "resetDatabaseProjectName", GoMethod: "ResetDatabaseProjectName"},
			_jsii_.MemberMethod{JsiiMethod: "resetDirectoryId", GoMethod: "ResetDirectoryId"},
			_jsii_.MemberMethod{JsiiMethod: "resetDirectoryPath", GoMethod: "ResetDirectoryPath"},
			_jsii_.MemberMethod{JsiiMethod: "resetExperimentId", GoMethod: "ResetExperimentId"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetInstancePoolId", GoMethod: "ResetInstancePoolId"},
			_jsii_.MemberMethod{JsiiMethod: "resetJobId", GoMethod: "ResetJobId"},
			_jsii_.MemberMethod{JsiiMethod: "resetKnowledgeAssistantId", GoMethod: "ResetKnowledgeAssistantId"},
			_jsii_.MemberMethod{JsiiMethod: "resetNotebookId", GoMethod: "ResetNotebookId"},
			_jsii_.MemberMethod{JsiiMethod: "resetNotebookPath", GoMethod: "ResetNotebookPath"},
			_jsii_.MemberMethod{JsiiMethod: "resetObjectType", GoMethod: "ResetObjectType"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPipelineId", GoMethod: "ResetPipelineId"},
			_jsii_.MemberMethod{JsiiMethod: "resetProviderConfig", GoMethod: "ResetProviderConfig"},
			_jsii_.MemberMethod{JsiiMethod: "resetRegisteredModelId", GoMethod: "ResetRegisteredModelId"},
			_jsii_.MemberMethod{JsiiMethod: "resetRepoId", GoMethod: "ResetRepoId"},
			_jsii_.MemberMethod{JsiiMethod: "resetRepoPath", GoMethod: "ResetRepoPath"},
			_jsii_.MemberMethod{JsiiMethod: "resetServingEndpointId", GoMethod: "ResetServingEndpointId"},
			_jsii_.MemberMethod{JsiiMethod: "resetSqlAlertId", GoMethod: "ResetSqlAlertId"},
			_jsii_.MemberMethod{JsiiMethod: "resetSqlDashboardId", GoMethod: "ResetSqlDashboardId"},
			_jsii_.MemberMethod{JsiiMethod: "resetSqlEndpointId", GoMethod: "ResetSqlEndpointId"},
			_jsii_.MemberMethod{JsiiMethod: "resetSqlQueryId", GoMethod: "ResetSqlQueryId"},
			_jsii_.MemberMethod{JsiiMethod: "resetSupervisorAgentId", GoMethod: "ResetSupervisorAgentId"},
			_jsii_.MemberMethod{JsiiMethod: "resetVectorSearchEndpointId", GoMethod: "ResetVectorSearchEndpointId"},
			_jsii_.MemberMethod{JsiiMethod: "resetWorkspaceFileId", GoMethod: "ResetWorkspaceFileId"},
			_jsii_.MemberMethod{JsiiMethod: "resetWorkspaceFilePath", GoMethod: "ResetWorkspaceFilePath"},
			_jsii_.MemberProperty{JsiiProperty: "servingEndpointId", GoGetter: "ServingEndpointId"},
			_jsii_.MemberProperty{JsiiProperty: "servingEndpointIdInput", GoGetter: "ServingEndpointIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "sqlAlertId", GoGetter: "SqlAlertId"},
			_jsii_.MemberProperty{JsiiProperty: "sqlAlertIdInput", GoGetter: "SqlAlertIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "sqlDashboardId", GoGetter: "SqlDashboardId"},
			_jsii_.MemberProperty{JsiiProperty: "sqlDashboardIdInput", GoGetter: "SqlDashboardIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "sqlEndpointId", GoGetter: "SqlEndpointId"},
			_jsii_.MemberProperty{JsiiProperty: "sqlEndpointIdInput", GoGetter: "SqlEndpointIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "sqlQueryId", GoGetter: "SqlQueryId"},
			_jsii_.MemberProperty{JsiiProperty: "sqlQueryIdInput", GoGetter: "SqlQueryIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "supervisorAgentId", GoGetter: "SupervisorAgentId"},
			_jsii_.MemberProperty{JsiiProperty: "supervisorAgentIdInput", GoGetter: "SupervisorAgentIdInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "vectorSearchEndpointId", GoGetter: "VectorSearchEndpointId"},
			_jsii_.MemberProperty{JsiiProperty: "vectorSearchEndpointIdInput", GoGetter: "VectorSearchEndpointIdInput"},
			_jsii_.MemberMethod{JsiiMethod: "with", GoMethod: "With"},
			_jsii_.MemberProperty{JsiiProperty: "workspaceFileId", GoGetter: "WorkspaceFileId"},
			_jsii_.MemberProperty{JsiiProperty: "workspaceFileIdInput", GoGetter: "WorkspaceFileIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "workspaceFilePath", GoGetter: "WorkspaceFilePath"},
			_jsii_.MemberProperty{JsiiProperty: "workspaceFilePathInput", GoGetter: "WorkspaceFilePathInput"},
		},
		func() interface{} {
			j := jsiiProxy_Permissions{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-databricks.permissions.PermissionsAccessControl",
		reflect.TypeOf((*PermissionsAccessControl)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktn/provider-databricks.permissions.PermissionsAccessControlList",
		reflect.TypeOf((*PermissionsAccessControlList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_PermissionsAccessControlList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktn/provider-databricks.permissions.PermissionsAccessControlOutputReference",
		reflect.TypeOf((*PermissionsAccessControlOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "groupName", GoGetter: "GroupName"},
			_jsii_.MemberProperty{JsiiProperty: "groupNameInput", GoGetter: "GroupNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "permissionLevel", GoGetter: "PermissionLevel"},
			_jsii_.MemberProperty{JsiiProperty: "permissionLevelInput", GoGetter: "PermissionLevelInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupName", GoMethod: "ResetGroupName"},
			_jsii_.MemberMethod{JsiiMethod: "resetPermissionLevel", GoMethod: "ResetPermissionLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetServicePrincipalName", GoMethod: "ResetServicePrincipalName"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserName", GoMethod: "ResetUserName"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "servicePrincipalName", GoGetter: "ServicePrincipalName"},
			_jsii_.MemberProperty{JsiiProperty: "servicePrincipalNameInput", GoGetter: "ServicePrincipalNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "userName", GoGetter: "UserName"},
			_jsii_.MemberProperty{JsiiProperty: "userNameInput", GoGetter: "UserNameInput"},
		},
		func() interface{} {
			j := jsiiProxy_PermissionsAccessControlOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-databricks.permissions.PermissionsConfig",
		reflect.TypeOf((*PermissionsConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-databricks.permissions.PermissionsProviderConfig",
		reflect.TypeOf((*PermissionsProviderConfig)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktn/provider-databricks.permissions.PermissionsProviderConfigOutputReference",
		reflect.TypeOf((*PermissionsProviderConfigOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetWorkspaceId", GoMethod: "ResetWorkspaceId"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "workspaceId", GoGetter: "WorkspaceId"},
			_jsii_.MemberProperty{JsiiProperty: "workspaceIdInput", GoGetter: "WorkspaceIdInput"},
		},
		func() interface{} {
			j := jsiiProxy_PermissionsProviderConfigOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnComplexObject)
			return &j
		},
	)
}
