// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

//go:build no_runtime_type_checking

package datadatabricksexternallocation

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validatePutManagedAqsParameters(value *DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueManagedAqs) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validatePutManagedPubsubParameters(value *DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueManagedPubsub) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validatePutManagedSqsParameters(value *DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueManagedSqs) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validatePutProvidedAqsParameters(value *DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueProvidedAqs) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validatePutProvidedPubsubParameters(value *DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueProvidedPubsub) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validatePutProvidedSqsParameters(value *DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueProvidedSqs) error {
	return nil
}

func (d *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateSetInternalValueParameters(val *DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueue) error {
	return nil
}

func (j *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewDataDatabricksExternalLocationExternalLocationInfoEffectiveFileEventQueueOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

