// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-databricks.provider.DatabricksProvider",
		reflect.TypeOf((*DatabricksProvider)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accountId", GoGetter: "AccountId"},
			_jsii_.MemberProperty{JsiiProperty: "accountIdInput", GoGetter: "AccountIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "actionsIdTokenRequestToken", GoGetter: "ActionsIdTokenRequestToken"},
			_jsii_.MemberProperty{JsiiProperty: "actionsIdTokenRequestTokenInput", GoGetter: "ActionsIdTokenRequestTokenInput"},
			_jsii_.MemberProperty{JsiiProperty: "actionsIdTokenRequestUrl", GoGetter: "ActionsIdTokenRequestUrl"},
			_jsii_.MemberProperty{JsiiProperty: "actionsIdTokenRequestUrlInput", GoGetter: "ActionsIdTokenRequestUrlInput"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "alias", GoGetter: "Alias"},
			_jsii_.MemberProperty{JsiiProperty: "aliasInput", GoGetter: "AliasInput"},
			_jsii_.MemberProperty{JsiiProperty: "audience", GoGetter: "Audience"},
			_jsii_.MemberProperty{JsiiProperty: "audienceInput", GoGetter: "AudienceInput"},
			_jsii_.MemberProperty{JsiiProperty: "authType", GoGetter: "AuthType"},
			_jsii_.MemberProperty{JsiiProperty: "authTypeInput", GoGetter: "AuthTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "azureClientId", GoGetter: "AzureClientId"},
			_jsii_.MemberProperty{JsiiProperty: "azureClientIdInput", GoGetter: "AzureClientIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "azureClientSecret", GoGetter: "AzureClientSecret"},
			_jsii_.MemberProperty{JsiiProperty: "azureClientSecretInput", GoGetter: "AzureClientSecretInput"},
			_jsii_.MemberProperty{JsiiProperty: "azureEnvironment", GoGetter: "AzureEnvironment"},
			_jsii_.MemberProperty{JsiiProperty: "azureEnvironmentInput", GoGetter: "AzureEnvironmentInput"},
			_jsii_.MemberProperty{JsiiProperty: "azureLoginAppId", GoGetter: "AzureLoginAppId"},
			_jsii_.MemberProperty{JsiiProperty: "azureLoginAppIdInput", GoGetter: "AzureLoginAppIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "azureTenantId", GoGetter: "AzureTenantId"},
			_jsii_.MemberProperty{JsiiProperty: "azureTenantIdInput", GoGetter: "AzureTenantIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "azureUseMsi", GoGetter: "AzureUseMsi"},
			_jsii_.MemberProperty{JsiiProperty: "azureUseMsiInput", GoGetter: "AzureUseMsiInput"},
			_jsii_.MemberProperty{JsiiProperty: "azureWorkspaceResourceId", GoGetter: "AzureWorkspaceResourceId"},
			_jsii_.MemberProperty{JsiiProperty: "azureWorkspaceResourceIdInput", GoGetter: "AzureWorkspaceResourceIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "clientId", GoGetter: "ClientId"},
			_jsii_.MemberProperty{JsiiProperty: "clientIdInput", GoGetter: "ClientIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientSecret", GoGetter: "ClientSecret"},
			_jsii_.MemberProperty{JsiiProperty: "clientSecretInput", GoGetter: "ClientSecretInput"},
			_jsii_.MemberProperty{JsiiProperty: "cloud", GoGetter: "Cloud"},
			_jsii_.MemberProperty{JsiiProperty: "cloudInput", GoGetter: "CloudInput"},
			_jsii_.MemberProperty{JsiiProperty: "clusterId", GoGetter: "ClusterId"},
			_jsii_.MemberProperty{JsiiProperty: "clusterIdInput", GoGetter: "ClusterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "configFile", GoGetter: "ConfigFile"},
			_jsii_.MemberProperty{JsiiProperty: "configFileInput", GoGetter: "ConfigFileInput"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "databricksCliPath", GoGetter: "DatabricksCliPath"},
			_jsii_.MemberProperty{JsiiProperty: "databricksCliPathInput", GoGetter: "DatabricksCliPathInput"},
			_jsii_.MemberProperty{JsiiProperty: "databricksIdTokenFilepath", GoGetter: "DatabricksIdTokenFilepath"},
			_jsii_.MemberProperty{JsiiProperty: "databricksIdTokenFilepathInput", GoGetter: "DatabricksIdTokenFilepathInput"},
			_jsii_.MemberProperty{JsiiProperty: "debugHeaders", GoGetter: "DebugHeaders"},
			_jsii_.MemberProperty{JsiiProperty: "debugHeadersInput", GoGetter: "DebugHeadersInput"},
			_jsii_.MemberProperty{JsiiProperty: "debugTruncateBytes", GoGetter: "DebugTruncateBytes"},
			_jsii_.MemberProperty{JsiiProperty: "debugTruncateBytesInput", GoGetter: "DebugTruncateBytesInput"},
			_jsii_.MemberProperty{JsiiProperty: "disableOauthRefreshToken", GoGetter: "DisableOauthRefreshToken"},
			_jsii_.MemberProperty{JsiiProperty: "disableOauthRefreshTokenInput", GoGetter: "DisableOauthRefreshTokenInput"},
			_jsii_.MemberProperty{JsiiProperty: "discoveryUrl", GoGetter: "DiscoveryUrl"},
			_jsii_.MemberProperty{JsiiProperty: "discoveryUrlInput", GoGetter: "DiscoveryUrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberProperty{JsiiProperty: "googleCredentials", GoGetter: "GoogleCredentials"},
			_jsii_.MemberProperty{JsiiProperty: "googleCredentialsInput", GoGetter: "GoogleCredentialsInput"},
			_jsii_.MemberProperty{JsiiProperty: "googleServiceAccount", GoGetter: "GoogleServiceAccount"},
			_jsii_.MemberProperty{JsiiProperty: "googleServiceAccountInput", GoGetter: "GoogleServiceAccountInput"},
			_jsii_.MemberProperty{JsiiProperty: "host", GoGetter: "Host"},
			_jsii_.MemberProperty{JsiiProperty: "hostInput", GoGetter: "HostInput"},
			_jsii_.MemberProperty{JsiiProperty: "httpTimeoutSeconds", GoGetter: "HttpTimeoutSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "httpTimeoutSecondsInput", GoGetter: "HttpTimeoutSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "metaAttributes", GoGetter: "MetaAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "metadataServiceUrl", GoGetter: "MetadataServiceUrl"},
			_jsii_.MemberProperty{JsiiProperty: "metadataServiceUrlInput", GoGetter: "MetadataServiceUrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "oauthCallbackPort", GoGetter: "OauthCallbackPort"},
			_jsii_.MemberProperty{JsiiProperty: "oauthCallbackPortInput", GoGetter: "OauthCallbackPortInput"},
			_jsii_.MemberProperty{JsiiProperty: "oidcTokenEnv", GoGetter: "OidcTokenEnv"},
			_jsii_.MemberProperty{JsiiProperty: "oidcTokenEnvInput", GoGetter: "OidcTokenEnvInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "password", GoGetter: "Password"},
			_jsii_.MemberProperty{JsiiProperty: "passwordInput", GoGetter: "PasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "profile", GoGetter: "Profile"},
			_jsii_.MemberProperty{JsiiProperty: "profileInput", GoGetter: "ProfileInput"},
			_jsii_.MemberProperty{JsiiProperty: "rateLimit", GoGetter: "RateLimit"},
			_jsii_.MemberProperty{JsiiProperty: "rateLimitInput", GoGetter: "RateLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccountId", GoMethod: "ResetAccountId"},
			_jsii_.MemberMethod{JsiiMethod: "resetActionsIdTokenRequestToken", GoMethod: "ResetActionsIdTokenRequestToken"},
			_jsii_.MemberMethod{JsiiMethod: "resetActionsIdTokenRequestUrl", GoMethod: "ResetActionsIdTokenRequestUrl"},
			_jsii_.MemberMethod{JsiiMethod: "resetAlias", GoMethod: "ResetAlias"},
			_jsii_.MemberMethod{JsiiMethod: "resetAudience", GoMethod: "ResetAudience"},
			_jsii_.MemberMethod{JsiiMethod: "resetAuthType", GoMethod: "ResetAuthType"},
			_jsii_.MemberMethod{JsiiMethod: "resetAzureClientId", GoMethod: "ResetAzureClientId"},
			_jsii_.MemberMethod{JsiiMethod: "resetAzureClientSecret", GoMethod: "ResetAzureClientSecret"},
			_jsii_.MemberMethod{JsiiMethod: "resetAzureEnvironment", GoMethod: "ResetAzureEnvironment"},
			_jsii_.MemberMethod{JsiiMethod: "resetAzureLoginAppId", GoMethod: "ResetAzureLoginAppId"},
			_jsii_.MemberMethod{JsiiMethod: "resetAzureTenantId", GoMethod: "ResetAzureTenantId"},
			_jsii_.MemberMethod{JsiiMethod: "resetAzureUseMsi", GoMethod: "ResetAzureUseMsi"},
			_jsii_.MemberMethod{JsiiMethod: "resetAzureWorkspaceResourceId", GoMethod: "ResetAzureWorkspaceResourceId"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientId", GoMethod: "ResetClientId"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientSecret", GoMethod: "ResetClientSecret"},
			_jsii_.MemberMethod{JsiiMethod: "resetCloud", GoMethod: "ResetCloud"},
			_jsii_.MemberMethod{JsiiMethod: "resetClusterId", GoMethod: "ResetClusterId"},
			_jsii_.MemberMethod{JsiiMethod: "resetConfigFile", GoMethod: "ResetConfigFile"},
			_jsii_.MemberMethod{JsiiMethod: "resetDatabricksCliPath", GoMethod: "ResetDatabricksCliPath"},
			_jsii_.MemberMethod{JsiiMethod: "resetDatabricksIdTokenFilepath", GoMethod: "ResetDatabricksIdTokenFilepath"},
			_jsii_.MemberMethod{JsiiMethod: "resetDebugHeaders", GoMethod: "ResetDebugHeaders"},
			_jsii_.MemberMethod{JsiiMethod: "resetDebugTruncateBytes", GoMethod: "ResetDebugTruncateBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableOauthRefreshToken", GoMethod: "ResetDisableOauthRefreshToken"},
			_jsii_.MemberMethod{JsiiMethod: "resetDiscoveryUrl", GoMethod: "ResetDiscoveryUrl"},
			_jsii_.MemberMethod{JsiiMethod: "resetGoogleCredentials", GoMethod: "ResetGoogleCredentials"},
			_jsii_.MemberMethod{JsiiMethod: "resetGoogleServiceAccount", GoMethod: "ResetGoogleServiceAccount"},
			_jsii_.MemberMethod{JsiiMethod: "resetHost", GoMethod: "ResetHost"},
			_jsii_.MemberMethod{JsiiMethod: "resetHttpTimeoutSeconds", GoMethod: "ResetHttpTimeoutSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetMetadataServiceUrl", GoMethod: "ResetMetadataServiceUrl"},
			_jsii_.MemberMethod{JsiiMethod: "resetOauthCallbackPort", GoMethod: "ResetOauthCallbackPort"},
			_jsii_.MemberMethod{JsiiMethod: "resetOidcTokenEnv", GoMethod: "ResetOidcTokenEnv"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPassword", GoMethod: "ResetPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetProfile", GoMethod: "ResetProfile"},
			_jsii_.MemberMethod{JsiiMethod: "resetRateLimit", GoMethod: "ResetRateLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetRetryTimeoutSeconds", GoMethod: "ResetRetryTimeoutSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetScopes", GoMethod: "ResetScopes"},
			_jsii_.MemberMethod{JsiiMethod: "resetServerlessComputeId", GoMethod: "ResetServerlessComputeId"},
			_jsii_.MemberMethod{JsiiMethod: "resetSkipVerify", GoMethod: "ResetSkipVerify"},
			_jsii_.MemberMethod{JsiiMethod: "resetToken", GoMethod: "ResetToken"},
			_jsii_.MemberMethod{JsiiMethod: "resetUsername", GoMethod: "ResetUsername"},
			_jsii_.MemberMethod{JsiiMethod: "resetWarehouseId", GoMethod: "ResetWarehouseId"},
			_jsii_.MemberMethod{JsiiMethod: "resetWorkspaceId", GoMethod: "ResetWorkspaceId"},
			_jsii_.MemberProperty{JsiiProperty: "retryTimeoutSeconds", GoGetter: "RetryTimeoutSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "retryTimeoutSecondsInput", GoGetter: "RetryTimeoutSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "scopes", GoGetter: "Scopes"},
			_jsii_.MemberProperty{JsiiProperty: "scopesInput", GoGetter: "ScopesInput"},
			_jsii_.MemberProperty{JsiiProperty: "serverlessComputeId", GoGetter: "ServerlessComputeId"},
			_jsii_.MemberProperty{JsiiProperty: "serverlessComputeIdInput", GoGetter: "ServerlessComputeIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "skipVerify", GoGetter: "SkipVerify"},
			_jsii_.MemberProperty{JsiiProperty: "skipVerifyInput", GoGetter: "SkipVerifyInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformProviderSource", GoGetter: "TerraformProviderSource"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "token", GoGetter: "Token"},
			_jsii_.MemberProperty{JsiiProperty: "tokenInput", GoGetter: "TokenInput"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "username", GoGetter: "Username"},
			_jsii_.MemberProperty{JsiiProperty: "usernameInput", GoGetter: "UsernameInput"},
			_jsii_.MemberProperty{JsiiProperty: "warehouseId", GoGetter: "WarehouseId"},
			_jsii_.MemberProperty{JsiiProperty: "warehouseIdInput", GoGetter: "WarehouseIdInput"},
			_jsii_.MemberMethod{JsiiMethod: "with", GoMethod: "With"},
			_jsii_.MemberProperty{JsiiProperty: "workspaceId", GoGetter: "WorkspaceId"},
			_jsii_.MemberProperty{JsiiProperty: "workspaceIdInput", GoGetter: "WorkspaceIdInput"},
		},
		func() interface{} {
			j := jsiiProxy_DatabricksProvider{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformProvider)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-databricks.provider.DatabricksProviderConfig",
		reflect.TypeOf((*DatabricksProviderConfig)(nil)).Elem(),
	)
}
